# Generated by Django 4.2.7 on 2023-12-05 12:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rezume_app', '0003_comments_blogdetails'),
    ]

    operations = [
        migrations.AlterField(
            model_name='blogdetails',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to=''),
        ),
        migrations.AlterField(
            model_name='blogdetails',
            name='text',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='blogdetails',
            name='title',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
